# Site settings
title: Codeando | Plataforma de cursos
description: "Cursos y tutoriales de programación y desarrollo web"
url: "http://www.codeando.org"
author:
  name: "Paulo Andrade"
  email: "source.compu@gmail.com"
  url: "http://codeandomx.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
comments: true

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: true
